#!/bin/bash

# Add some colours
red='\033[1;31m'
green='\033[1;32m'
yellow='\033[1;33m'
blue='\033[1;34m'
light_cyan='\033[1;96m'
reset='\033[0m'

tell () {
#function_version: v0.1-alpha
    [[ $1 == "d" ]] && mgs="${yellow} >>${light_cyan} "
    [[ $1 == "i" ]] && mgs="${yellow}  ⃝¡${blue} "
    [[ $1 == "s" ]] && mgs="${green} ✓⃝${light_cyan} "
    [[ $1 == "f" ]] && mgs="${red} ✗⃝ ${red} "
    printf "${mgs} ${2} ${reset}\n\n"
}

