#!/bin/bash

get_arch() {
    #version: 0.1-alpha
    case $(getprop ro.product.cpu.abi) in
    arm64-v8a)
        SYS_ARCH=arm64
        ;;
    armeabi | armeabi-v7a)
        SYS_ARCH=armhf
        ;;
    x86)
        SYS_ARCH=x86
        ;;
    x84_64)
        SYS_ARCH=x86_64
        ;;
    *)
        unsupported_arch
        ;;
    esac
}
